name: SSH Docker Deploy
description: Deploy dockerized service to remote server via SSH

inputs:
  server-user:
    required: true
  server-host:
    required: true
  ssh-port:
    required: true    
  ssh-private-key:
    required: true

  service-folder:
    required: true

  container-name:
    required: true
  image:
    required: true

  env-file:
    required: true

  registry-url:
    required: true
  registry-user:
    required: true
  registry-token:
    required: true

  docker-network:
    required: false
    default: npm_default
  docker-memory:
    required: false
    default: 2g
  extra-docker-args:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Prepare SSH key
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
      run: |
        set -euo pipefail
        umask 077
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        echo "SSH_KEY_PATH=$PWD/ssh_key" >> "$GITHUB_ENV"

    - name: Create env file
      shell: bash
      run: |
        set -euo pipefail
        echo "${{ inputs.env-file }}" > app.env

    - name: Prepare remote folders
      shell: bash
      run: |
        set -euo pipefail
        ssh -i "$SSH_KEY_PATH" -p "${{ inputs.ssh-port }}" -o StrictHostKeyChecking=no "${{ inputs.server-user }}@${{ inputs.server-host }}" "mkdir -p '${{ inputs.service-folder }}'; cd '${{ inputs.service-folder }}'; touch .env"

    - name: Upload env file
      shell: bash
      run: |
        set -euo pipefail
        scp -i "$SSH_KEY_PATH" -P "${{ inputs.ssh-port }}" -o StrictHostKeyChecking=no app.env "${{ inputs.server-user }}@${{ inputs.server-host }}:${{ inputs.service-folder }}/.env"
        rm -f app.env

    - name: Deploy container
      shell: bash
      run: |
        set -euo pipefail
        ssh -i "$SSH_KEY_PATH" -p "${{ inputs.ssh-port }}" -o StrictHostKeyChecking=no "${{ inputs.server-user }}@${{ inputs.server-host }}" "
          cd '${{ inputs.service-folder }}';
          docker login -u '${{ inputs.registry-user }}' -p '${{ inputs.registry-token }}' '${{ inputs.registry-url }}';
          docker pull '${{ inputs.image }}';
          docker container rm -f '${{ inputs.container-name }}' || true;
          docker run -d -i --name '${{ inputs.container-name }}' --env-file ./.env --network='${{ inputs.docker-network }}' --memory='${{ inputs.docker-memory }}' --restart=always --volume '${{ inputs.service-folder }}/files:/app/files' ${{ inputs.extra-docker-args }} '${{ inputs.image }}';

          docker image prune -f;
          docker system prune -f;          
        "

    - name: Cleanup SSH key
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        rm -f "$SSH_KEY_PATH" || true
