.docker_build:
  interruptible: true
  image: docker:27-cli
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - api_failure
  before_script:
    - unset DOCKER_HOST
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN $CI_REGISTRY
  script:
    - cp "$NUGET_CONFIG_FILE" "$PROJECT_FOLDER/nuget.config"
    - DF="$PROJECT_FOLDER/$SERVICE_FOLDER/Dockerfile"
    - 'sed -i -E "s#^(RUN[[:space:]]+)(dotnet[[:space:]]+(restore|build|publish|run))#\1--mount=type=cache,id=nuget-packages,target=/var/cache/nuget,sharing=locked NUGET_PACKAGES=/var/cache/nuget \2#" "$DF"'
    - docker buildx build --provenance=false --sbom=false --push -t $IMAGE_REGISTRY_PATH -t $LATEST_IMAGE_REGISTRY_PATH -f "$DF" ./$PROJECT_FOLDER/$CONTEXT_FOLDER
