variables:
  DOCKER_COMPOSE_PATH: .

  PROJECT_FOLDER: .
  CONTEXT_FOLDER: .

  ENV_SUFFIX: "unknown"
  SERVICE_REGISTRY_PATH : $CI_REGISTRY_IMAGE/$SERVICE_NAME/$ENV_SUFFIX

  IMAGE_REGISTRY_PATH: $SERVICE_REGISTRY_PATH:$CI_PIPELINE_ID
  LATEST_IMAGE_REGISTRY_PATH: $SERVICE_REGISTRY_PATH:latest

  SERVICE_NAME_ENV: $SERVICE_NAME$CONTUR_NAME-$ENV_SUFFIX
  SERVER_SERVICE_FOLDER: /home/$SERVICE_NAME_ENV

  SERVER_WWWROOT_SERVICE_FOLDER: $SERVER_SERVICE_FOLDER/wwwroot/Uploads
  SERVICE_WWWROOT_FOLDER: /app/wwwroot/Uploads

  EXTRA_VOLUMES: ""
  DOCKER_BUILDKIT: "1"
