variables:
  REGISTRY_PROJECT_PATH: dotnet/project
  DOCKER_COMPOSE_PATH: .

  PROJECT_FOLDER: .
  CONTEXT_FOLDER: .

  SERVICE_REGISTRY_PATH : $CI_REGISTRY/$REGISTRY_PROJECT_PATH/$SERVICE_NAME 

  IMAGE_REGISTRY_PATH: $SERVICE_REGISTRY_PATH:$CI_PIPELINE_ID  
  LATEST_IMAGE_REGISTRY_PATH: $SERVICE_REGISTRY_PATH:latest
  LATEST_IMAGE_REGISTRY_PATH_WITH_ENV: $LATEST_IMAGE_REGISTRY_PATH-$ENV_SUFFIX

  SERVICE_NAME_ENV: $SERVICE_NAME$CONTUR_NAME-$ENV_SUFFIX
  SERVER_SERVICE_FOLDER: /home/$SERVICE_NAME_ENV

  SERVER_WWWROOT_SERVICE_FOLDER: $SERVER_SERVICE_FOLDER/wwwroot/Uploads
  SERVICE_WWWROOT_FOLDER: /app/wwwroot/Uploads