.notify_telegram:
  image: alpine/curl:latest
  before_script:
    - apk add --no-cache curl jq
  script:
    - |
      set -euo pipefail

      # --- Список задач пайплайна ---
      JOBS=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs")

      FAILED_JOBS=$(echo "$JOBS" | jq -r '.[] | select(.status == "failed") | .name' | paste -sd ', \n ' -)
      SUCCESSFUL_JOBS=$(echo "$JOBS" | jq -r '.[] | select(.status == "success") | .name' | paste -sd ', \n ' -)
      CANCELED_JOBS=$(echo "$JOBS" | jq -r '.[] | select(.status == "canceled") | .name' | paste -sd ', \n ' -)
      SKIPPED_JOBS=$(echo "$JOBS" | jq -r '.[] | select(.status == "skipped") | .name' | paste -sd ', \n ' -)

      DETAILS=""
      if [ -n "$SUCCESSFUL_JOBS" ]; then
        DETAILS="${DETAILS} \n ✅ *Успешные задачи:* \n ${SUCCESSFUL_JOBS} \n "
      fi
      if [ -n "$FAILED_JOBS" ]; then
        DETAILS="${DETAILS} \n ❌ *Неуспешные задачи:* \n ${FAILED_JOBS} \n "
      fi
      if [ -n "$CANCELED_JOBS" ]; then
        DETAILS="${DETAILS} \n 🚫 *Отмененные задачи:* \n ${CANCELED_JOBS} \n "
      fi
      if [ -n "$SKIPPED_JOBS" ]; then
        DETAILS="${DETAILS} \n ⏭️ *Пропущенные задачи:* \n ${SKIPPED_JOBS} \n "
      fi

      # --- Общий статус ---
      if [ -z "$FAILED_JOBS" ] && [ -z "$CANCELED_JOBS" ]; then
        STATUS="✅ Пайплайн *${CI_PIPELINE_ID}* завершился *успешно*."
      else
        STATUS="❌ Пайплайн *${CI_PIPELINE_ID}* завершился с *ошибками*."
      fi

      # --- Достаём информацию о MR ---
      MR_IID="${CI_MERGE_REQUEST_IID:-}"
      MR_INFO=""
      if [ -n "$MR_IID" ]; then
        # MR pipeline
        MR_INFO=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$MR_IID")
      else
        # post-merge / обычный pipeline — ищем MR по коммиту
        MR_FROM_COMMIT=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/merge_requests")
        MR_IID=$(echo "$MR_FROM_COMMIT" | jq -r '.[0].iid // empty')
        if [ -n "$MR_IID" ]; then
          MR_INFO=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
            "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$MR_IID")
        fi
      fi

      MR_AUTHOR=""
      MR_MERGED_BY=""
      MR_TITLE=""
      MR_URL=""
      if [ -n "$MR_INFO" ]; then
        MR_AUTHOR=$(echo "$MR_INFO" | jq -r '.author.name // empty')
        MR_MERGED_BY=$(echo "$MR_INFO" | jq -r '.merged_by.name // empty')
        MR_TITLE=$(echo "$MR_INFO" | jq -r '.title // empty')
        MR_URL=$(echo "$MR_INFO" | jq -r '.web_url // empty')
      fi

      # --- Формируем блок автора/мерджера ---
      AUTHOR_BLOCK=""
      if [ -n "$MR_AUTHOR" ]; then
        AUTHOR_BLOCK="${AUTHOR_BLOCK}\n- Автор MR: *${MR_AUTHOR}*"
      fi
      if [ -n "$MR_MERGED_BY" ]; then
        AUTHOR_BLOCK="${AUTHOR_BLOCK}\n- Замержил: *${MR_MERGED_BY}*"
      fi
      if [ -z "$AUTHOR_BLOCK" ]; then
        # Нет MR (или не нашли) — показываем инициатора пайплайна
        AUTHOR_BLOCK="\n- Инициатор: *${GITLAB_USER_NAME}*"
      fi

      # --- (опционально) Ссылка на MR, если нашли ---
      MR_LINE=""
      if [ -n "$MR_URL" ] && [ -n "$MR_TITLE" ]; then
        MR_LINE="\n- MR: [${MR_TITLE}](${MR_URL})"
      fi

      # --- Получаем URL окружения из GitLab API ---
      ENV_URL=""
      if [ -n "$DEPLOY_ENV" ]; then
        ENVIRONMENTS_JSON=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
            "$CI_API_V4_URL/projects/$CI_PROJECT_ID/environments")

        ENV_URL=$(echo "$ENVIRONMENTS_JSON" | jq -r --arg NAME "$DEPLOY_ENV" '.[] | select(.name == $NAME) | .external_url // empty')
        fi

      if [ -n "$ENV_URL" ]; then
        ENV_LINE="\n- URL: [${ENV_URL}](${ENV_URL})"
      else
        ENV_LINE="\n- URL: (не найдено)"
      fi

      # --- Итоговый текст ---
      TEXT="$STATUS \n${DETAILS} 📝 *Информация о сборке:* \n- Проект: *${CI_PROJECT_NAME}* \n- Ветка: *${CI_COMMIT_REF_NAME}*${AUTHOR_BLOCK}${MR_LINE}${ENV_LINE}"

      # --- Отправляем в Telegram ---
      curl -s --header 'Content-Type: application/json' \
        --request 'POST' \
        --data "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$TEXT\", \"parse_mode\": \"Markdown\"}" \
        "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" 
  when: always
  allow_failure: true
  dependencies: []
