name: Dotnet Pack
description: Restore, build and pack .NET project

inputs:
  project_folder:
    required: true
  output_folder:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json

    - name: Restore
      run: dotnet restore ${{ inputs.project_folder }}
      shell: bash

    - name: Pack
      run: dotnet pack ${{ inputs.project_folder }} --configuration Release --output ${{ inputs.output_folder }} --no-restore
      shell: bash
