name: Dotnet EF Migrator
description: Build and run EF migrator docker image

inputs:
  registry-user:
    required: true
  registry-token:
    required: true
  env-file:
    required: true
  project-folder:
    required: true
  migrator-folder:
    required: true
  migrator-project:
    required: true
  nuget-config:
    required: false
  nuget-provider:
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Create nuget.config
      if: ${{ inputs.nuget-config != '' }}
      shell: bash
      env:
        NUGET_CONFIG: ${{ inputs.nuget-config }}
        NUGET_PROVIDER: ${{ inputs.nuget-provider }}
        REGISTRY_USER: ${{ inputs.registry-user }}
        REGISTRY_TOKEN: ${{ inputs.registry-token }}
      run: |
        echo "$NUGET_CONFIG" | envsubst > ${{ inputs.project-folder }}/nuget.config

    - name: Create .env for migrator
      shell: bash
      run: |
        echo "${{ inputs.env-file }}" > "${{ inputs.migrator-folder }}/.env"

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Build migrator image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.project-folder }}
        file: ${{ inputs.project-folder }}/${{ inputs.migrator-folder }}/Dockerfile
        push: false
        load: true
        tags: migrator-image
        build-args: |
          BUILD_CONFIGURATION=Release

        cache-from: type=gha,scope=${{ github.repository }}-migrator
        cache-to: type=gha,mode=max,scope=${{ github.repository }}-migrator

    - name: Run migrations
      shell: bash
      run: |
        docker run --rm --env-file "${{ inputs.migrator-folder }}/.env" migrator-image
