on:
  workflow_call:
    inputs:
      project_folder:
        type: string
        default: "."
      output_folder:
        type: string
        default: "./out"
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: PANiXiDA-Infrastructure/ci-cd/.github/actions/dotnet-pack@main
        with:
          project_folder: ${{ inputs.project_folder }}
          output_folder: ${{ inputs.output_folder }}

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "${{ inputs.output_folder }}/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}"
  
